Controllers/IyzicoSettingsController.cs
namespace Nop.Plugin.Payments.Iyzico.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Nop.Plugin.Payments.Iyzico.Models;
    using Nop.Plugin.Payments.Iyzico.Validators;
    using Nop.Services.Configuration;
    using Nop.Services.Localization;
    using Nop.Services.Messages;
    using Nop.Services.Security;
    using Nop.Web.Framework;
    using Nop.Web.Framework.Controllers;
    using Nop.Web.Framework.Mvc.Filters;

    [Area(AreaNames.Admin)]
    [AuthorizeAdmin(false)]
    public class IyzicoSettingsController : BasePluginController
    {
        #region Fields
        private readonly ISettingService _settingService;
        private readonly ILocalizationService _localizationService;
        private readonly IPermissionService _permissionService;
        private readonly INotificationService _notificationService;
        private readonly IyzicoSettings _iyzicoSettings;
        #endregion

        #region Ctor
        public IyzicoSettingsController(ISettingService settingService,
            ILocalizationService localizationService,
            IPermissionService permissionService,
            INotificationService notificationService,
            IyzicoSettings iyzicoSettings)
        {
            _settingService = settingService;
            _localizationService = localizationService;
            _permissionService = permissionService;
            _notificationService = notificationService;
            _iyzicoSettings = iyzicoSettings;
        }
        #endregion

        #region Methods

        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Configure()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageShippingSettings))
                return AccessDeniedView();

            var model = new ConfigurationModel()
            {
                ApiKey = _iyzicoSettings.ApiKey,
                SecretKey = _iyzicoSettings.SecretKey,
                BaseUrl = _iyzicoSettings.BaseUrl,
                PaymentMethodDescription = _iyzicoSettings.PaymentMethodDescription,
                CheckoutCookieExpires = _iyzicoSettings.CheckoutCookieExpires,
                Enable3DSecure = _iyzicoSettings.Enable3DSecure
            };

            return View($"{IyzicoDefaults.IYZICO_CONFIGURE_VIEWS_PATH}/Configure.cshtml", model);
        }

        [AutoValidateAntiforgeryToken]
        [HttpPost, ActionName("Configure")]
        [FormValueRequired("save")]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return await Configure();

            //validate configuration (custom validation)
            var validationResult = new ConfigurationValidator(_localizationService).Validate(model);
            if (!validationResult.IsValid)
                return await Configure();

            _iyzicoSettings.ApiKey = model.ApiKey;
            _iyzicoSettings.SecretKey = model.SecretKey;
            _iyzicoSettings.BaseUrl = model.BaseUrl;
            _iyzicoSettings.PaymentMethodDescription = model.PaymentMethodDescription;
            _iyzicoSettings.CheckoutCookieExpires = model.CheckoutCookieExpires;
            _iyzicoSettings.Enable3DSecure = model.Enable3DSecure;

            await _settingService.SaveSettingAsync(_iyzicoSettings);
            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));
            return View($"{IyzicoDefaults.IYZICO_CONFIGURE_VIEWS_PATH}/Configure.cshtml", model);
        }
        
        #endregion
    }
}

Views/Configure/Configure.cshtml
@model Nop.Plugin.Payments.Iyzico.Models.ConfigurationModel

@{
    Layout = "_ConfigurePlugin";
}

<div class="row">
    <div class="col-md-12">
        @* <form asp-area="Admin" asp-controller="IyzicoSettings" asp-action="Configure" method="post"> ...</form> => action="/Plugins/Iyzico/Configure" *@
        <form asp-route="@IyzicoDefaults.ConfigurationRouteName" method="post">
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-body">

                        <div class="row">
                            <div class="col-md-9 offset-md-3">
                                <div>
                                    <p>
                                        Eyüp Gevenim 
                                        <a href="https://www.linkedin.com/in/eyupgevenim" target="_top">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                                                <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z" />
                                            </svg>
                                            Linkedin
                                        </a>   
                                        <a href="https://github.com/eyupgevenim" target="_top">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                                                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z" />
                                            </svg>
                                            GitHub
                                        </a>
                                        <br />
                                        <a href="https://github.com/eyupgevenim/Nop.Plugin.Payments.Iyzico" target="_top">Nop.Plugin.Payments.Iyzico</a> <br />

                                        <a href="https://dev.iyzipay.com/tr/api" target="_top">API Entegrasyonu</a> /
                                        <a href="https://dev.iyzipay.com/en/api" target="_top">API Integration</a> <br />
                                        <a href="https://github.com/iyzico/iyzipay-dotnet" target="_top">github.com iyzipay-dotnet</a> <br />
                                    </p>
                                    <br />
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group row">
                                    <div class="col-md-3">
                                        <nop-label asp-for="ApiKey" />
                                    </div>
                                    <div class="col-md-9">
                                        <nop-editor asp-for="ApiKey" />
                                        <span asp-validation-for="ApiKey"></span>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col-md-3">
                                        <nop-label asp-for="SecretKey" />
                                    </div>
                                    <div class="col-md-9">
                                        <nop-editor asp-for="SecretKey" />
                                        <span asp-validation-for="SecretKey"></span>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col-md-3">
                                        <nop-label asp-for="BaseUrl" />
                                    </div>
                                    <div class="col-md-9">
                                        <nop-editor asp-for="BaseUrl" />
                                        <span asp-validation-for="BaseUrl"></span>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col-md-3">
                                        <nop-label asp-for="PaymentMethodDescription" />
                                    </div>
                                    <div class="col-md-9">
                                        <nop-editor asp-for="PaymentMethodDescription" />
                                        <span asp-validation-for="PaymentMethodDescription"></span>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col-md-3">
                                        <nop-label asp-for="CheckoutCookieExpires" />
                                    </div>
                                    <div class="col-md-9">
                                        <nop-editor asp-for="CheckoutCookieExpires" />
                                        <span asp-validation-for="CheckoutCookieExpires"></span>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col-md-3">
                                        <nop-label asp-for="Enable3DSecure" />
                                    </div>
                                    <div class="col-md-9">
                                        <nop-editor asp-for="Enable3DSecure" />
                                        <span asp-validation-for="Enable3DSecure"></span>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col-md-3"></div>
                                    <div class="col-md-9">
                                        <input type="submit" name="save" class="btn bg-blue" value="@T("Admin.Common.Save")" />
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    function validateFloatKeyPress(el, evt) {
        var charCode = (evt.which) ? evt.which : event.keyCode;
        var number = el.value.split('.');
        if (charCode != 46 && charCode > 31 && (charCode < 48 || charCode > 57)) {
            return false;
        }
        if (number.length > 1 && charCode == 46) {
            return false;
        }
        var caratPos = getSelectionStart(el);
        var dotPos = el.value.indexOf(".");
        if (caratPos > dotPos && dotPos > -1 && (number[1].length > 1)) {
            return false;
        }
        return true;
    }
    function getSelectionStart(o) {
        if (o.createTextRange) {
            var r = document.selection.createRange().duplicate()
            r.moveEnd('character', o.value.length)
            if (r.text == '') return o.value.length
            return o.value.lastIndexOf(r.text)
        } else return o.selectionStart
    }
</script>